name: Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        name : Lint check
        steps:
            - uses: actions/checkout@v2
              name: Checkout repository
            - name: Python install
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.20
                  cache: pip
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: lint with flake8
              run: flake8 src/
            - name: Run tests
              run: pytest tests/ --junitxml=junit.xml

    deploy:
        runs-on: ubuntu-latest
        needs: lint
        if : github.ref == 'refs/heads/main'
        name : Deploy
        steps:
            - run: echo "Deploying on production"
              name: Deploy

